### ISSUE TITLE
Errors disappear after saving a large file

### ISSUE THREAD

**Issue by taranlu-houzz** [matangover/mypy-vscode#102]
I have a medium sized project that has some large individual Python files (~3.5K lines). When I run `mypy` via `Mypy: Recheck Workspace`, the errors are all properly highlighted, but when I fix an error, and save the file, all of the highlighting goes away and often does not return until I manually re-run `mpyp` on the workspace, which takes several seconds. I think the issue may not happen, or may be less pronounced for smaller files.

**Comment by matangover** [comment]
Interesting, I can't manage to reproduce this... I wonder if it happens when you run dmypy from the command line too?

**Comment by 9-2-1** [comment]
I also encountered this.

Errors shown after restart, disappeared after file changed.

Lots of AssertionError appeared in extension output after file changed.

```
Recheck complete
Document saved: d:\Documents\常用\blueberry\dev\blueberry.py
[11] Check folder: d:\Documents\常用\blueberry\dev
[11] Using extra arguments: --strict
[11] Received Python path from Python extension: c:\Users\11951\miniforge3\envs\blueberry\python.exe
[11] Running dmypy in folder d:\Documents\常用\blueberry\dev
'c:\Users\11951\miniforge3\envs\blueberry\python.exe' -m mypy.dmypy --status-file 'c:\Users\11951\AppData\Roaming\Trae CN\User\workspaceStorage\c1610941a67dab91ac743567fbba8128\matangover.mypy\dmypy-1caed0947a83bd647c618f6b2cb0f9127570d3b4-32400.json' run --log-file 'c:\Users\11951\AppData\Roaming\Trae CN\User\workspaceStorage\c1610941a67dab91ac743567fbba8128\matangover.mypy\dmypy-1caed0947a83bd647c618f6b2cb0f9127570d3b4.log' -- --python-executable 'c:\Users\11951\miniforge3\envs\blueberry\python.exe' . --show-error-end --no-error-summary --no-pretty --no-color-output --strict
[11] Error running mypy in d:\Documents\常用\blueberry\dev. See Output panel for details.
[11] stdout:
blueberry.py:678:31:678:48: error: Value of type variable "FmtT" of "fmt" cannot be "int | None"  [type-var]

[11] stderr:
Exception ignored in PyObject_HasAttr(); consider using PyObject_HasAttrWithError(), PyObject_GetOptionalAttr() or PyObject_GetAttr():
Traceback (most recent call last):
  File "mypy\nodes.py", line 615, in setter
AssertionError: 
Exception ignored in PyObject_HasAttr(); consider using PyObject_HasAttrWithError(), PyObject_GetOptionalAttr() or PyObject_GetAttr():
Traceback (most recent call last):
  File "mypy\nodes.py", line 615, in setter
AssertionError: 
Exception ignored in PyObject_HasAttr(); consider using PyObject_HasAttrWithError(), PyObject_GetOptionalAttr() or 

...

Exception ignored in PyObject_HasAttr(); consider using PyObject_HasAttrWithError(), PyObject_GetOptionalAttr() or PyObject_GetAttr():
Traceback (most recent call last):
  File "mypy\nodes.py", line 615, in setter
AssertionError: 
```

Environment:
```
> python --version
Python 3.13.5
> conda --version
conda 25.5.1
> trae --version
1.100.3
a7ae9ea3179791ca4094e059210331d416404dca
x64
```

**Comment by 9-2-1** [comment]
dmypy-1caed0947a83bd647c618f6b2cb0f9127570d3b4.log

```
Traceback (most recent call last):
  File "mypy\ipc.py", line 132, in write
BrokenPipeError: [WinError 232] 管道正在被关闭。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mypy\dmypy_server.py", line 249, in serve
  File "mypy\dmypy_util.py", line 43, in send
  File "mypy\ipc.py", line 148, in write
mypy.ipc.IPCException: Failed to write with error: 232
Traceback (most recent call last):
  File "mypy\ipc.py", line 132, in write
BrokenPipeError: [WinError 232] 管道正在被关闭。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mypy\dmypy\client.py", line 284, in main
  File "mypy\dmypy\client.py", line 638, in do_daemon
  File "mypy\dmypy_server.py", line 249, in serve
  File "mypy\dmypy_util.py", line 43, in send
  File "mypy\ipc.py", line 148, in write
mypy.ipc.IPCException: Failed to write with error: 232
```

**Comment by 9-2-1** [comment]
> run dmypy from the command line too?

Looks like that it may be dmypy's fault, AssertionError displayed, while it still produce correct stdout.

It may be better if the extension can ignore this type of error if report is printed through stdout.

**Comment by 9-2-1** [comment]
Downgrade python to 3.12 solved my problem (I noticed that conda also rollback mypy to 1.16.0)

**Comment by matangover** [comment]
@9-2-1 Thanks for reporting! Do you know if this is still reproducible?
