### ISSUE TITLE
mypy deamon crashing in my workspace

### ISSUE THREAD

**Issue by Agent-Hellboy** [matangover/mypy-vscode#57]
here is the error log
```
[29] stderr:
Daemon crashed!
Traceback (most recent call last):
  File "mypy/dmypy_server.py", line 230, in serve
  File "mypy/dmypy_server.py", line 273, in run_command
  File "mypy/dmypy_server.py", line 332, in cmd_run
  File "mypy/dmypy_server.py", line 389, in check
  File "mypy/dmypy_server.py", line 424, in initialize_fine_grained
  File "mypy/build.py", line 154, in build
  File "mypy/build.py", line 230, in _build
  File "mypy/build.py", line 2729, in dispatch
  File "mypy/build.py", line 3087, in process_graph
  File "mypy/build.py", line 3179, in process_stale_scc
  File "mypy/semanal_main.py", line 80, in semantic_analysis_for_scc
  File "mypy/semanal_main.py", line 203, in process_top_levels
  File "mypy/semanal_main.py", line 330, in semantic_analyze_target
  File "mypy/semanal.py", line 414, in refresh_partial
  File "mypy/semanal.py", line 427, in refresh_top_level
  File "mypy/semanal.py", line 498, in add_builtin_aliases
  File "mypy/semanal.py", line 528, in create_alias
  File "mypy/semanal.py", line 4738, in named_type_or_none
AssertionError: Var:nil(defaultdict)
```

I am using this 
```
from gevent import monkey

monkey.patch_all()
```
is it a cause for the crash?

**Comment by matangover** [comment]
Sorry, I can't help with that because it's a bug in mypy itself. Please report it to mypy issue tracker:

https://github.com/python/mypy/issues

**Comment by Agent-Hellboy** [comment]
Is there an existing issue for this? what is it?

**Comment by matangover** [comment]
I really don't know, but if there's an issue it would be reported there. You can search
